### ISSUE TITLE
Status Updates Do Not Apply For Individual Tracking #'s

### ISSUE THREAD

**Issue by qdd8jtl** [brcox90/CIMMigrationProject#4]
Source - MAN4, ID - 693, Assigned to - Pawel, Alt Auditor - Dom

- Marked tracking # 1ZAR97331438787108 as Audit

- Then marked tracking number 'X' below it as Invalid, but Audit status gets wiped out after selection.

- When selecting a Result, the last status marked also gets wiped out.
[Interim-StatusSelect-Gone.docx](https://github.com/brcox90/CIMMigrationProject/files/4027907/Interim-StatusSelect-Gone.docx)

**Comment by mikey2695** [comment]
Caused because MAN4 - US does not exist in the INTERIM_HISTORY table. Need to make sure all sources with complete descriptions are added for both countries.
