### ISSUE TITLE
Error Message Appears When Accessing Interim

### ISSUE THREAD

**Issue by qdd8jtl** [brcox90/CIMMigrationProject#5]
When clicking Interim Database from the main menu, a pop-up with the message 'Error:Invalid column name 'INTERIM_CRITERIA_STATUS.' appears before the Interim Database is loaded.

This message also appears any time anything else is clicked on the screen.
[Interim-ErrorMessage.docx](https://github.com/brcox90/CIMMigrationProject/files/4032721/Interim-ErrorMessage.docx)

**Comment by mikey2695** [comment]
Newest version had not been published, all done now. (version is 1.0.0.211)

**Comment by qdd8jtl** [comment]
Just downloaded the latest version.  The database crashes when clicking on Interim Database.

**Comment by Pawel062** [comment]
I get a crash when clicking on interim and then clicking daily.

**Comment by mikey2695** [comment]
Taken care of. When daily is clicked, if no scenarios have been imported for today's date, error check has been implemented.

**Comment by qdd8jtl** [comment]
Looks good!  Thank you
